name: 导出收藏夹

on:
  workflow_dispatch:
    inputs:
      DEBUG:
        description: '调试模式'
        type: boolean
        default: false


env:
  DEBUG: ${{ inputs.DEBUG && 'pica' }}
  PICA_IN_GITHUB: true # 用于区分运行环境，不要修改
  PICA_ACCOUNT: ${{ secrets.PICA_ACCOUNT }}
  PICA_PASSWORD: ${{ secrets.PICA_PASSWORD }}

  # 固定值
  ZIP_FP: /home/runner/work/comics/download/export.7z
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps and build
        run: |
          pnpm install
          pnpm run build

      - name: Print favorites content
        run: |
          echo "Printing favorites content:"
          pnpm print-favorites

      - name: Upload to github
        uses: actions/upload-artifact@v4
        with:
          name: '导出的收藏夹'
          path: ${{ env.ZIP_FP }}
          if-no-files-found: error
          retention-days: 90

