name: Export Favorites 

on:
  workflow_dispatch:
    inputs:
      PICA_PRINT_FAVS:
        description: '打印收藏夹的全部内容'
        type: boolean
        default: false


env:
  DEBUG: ${{ inputs.DEBUG && 'pica' }}
  PICA_PRINT_FAVS: ${{ 'true' }}
  PICA_IN_GITHUB: true # 用于区分运行环境，不要修改
  PICA_ACCOUNT: ${{ secrets.PICA_ACCOUNT }}
  PICA_PASSWORD: ${{ secrets.PICA_PASSWORD }}

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps and build
        run: |
          pnpm install
          pnpm run build

      - name: Download
        run: pnpm start

      - name: Compress
        if: inputs.OUTPUT_ZIP
        run: pnpm start:zip

      - name: Upload to github
        uses: actions/upload-artifact@v4
        with:
          name: pica-comics
          path: ${{ inputs.OUTPUT_ZIP && 'comics-zip/' || 'comics/' }}
          retention-days: 7

      - name: Print favorites content
        if: inputs.PICA_PRINT_FAVS
        run: |
          echo "Printing favorites content:"
          pnpm run print-favorites
        continue-on-error: true
        
      - name: 上传结果
        uses: actions/upload-artifact@v4
        with:
          name: '导出的收藏夹'
          path: ${{ env.ZIP_FP }}
          if-no-files-found: error
          retention-days: 90
